//! The front end minus the terminal. Nothing in this crate opens a terminal,
//! reads a key or owns an event loop: `src/main.rs` does all of that and hands
//! values in, which is what keeps the draw path assertable against an in-memory
//! buffer and everything else against plain values. Three modules reach past
//! that rule on purpose — `claude` runs the CLI as a child process because the
//! engine's port spawns nothing, `linear` opens a socket because the board is
//! somewhere else, and `watch` holds a filesystem watcher — and all three are
//! built so the decisions made about what they hear are values a test can drive
//! without any of them.

mod account;
mod app;
mod brief;
mod claude;
mod colour;
mod composer;
mod confirm;
#[cfg(test)]
mod fixture;
mod linear;
pub mod panel;
mod prompt;
mod selection;
mod submission;
mod template;
mod thread;
mod ui;
mod watch;
mod wrap;

pub use account::Account;
pub use account::Line;
pub use account::Outcome;
pub use account::Section;
pub use account::Voice;
pub use account::size;
pub use app::App;
pub use app::Chrome;
pub use app::Focus;
pub use app::PactIntent;
pub use app::PactToggle;
pub use app::Row;
pub use app::Run;
pub use app::RunHeader;
pub use app::Sigils;
pub use app::reseat_on;
pub use brief::Brief;
pub use brief::Error as BriefError;
pub use brief::ScopeBlock;
pub use brief::ScopeBlockError;
pub use brief::Slice;
pub use brief::brief_at;
pub use brief::scope_block_in;
pub use claude::Activities;
pub use claude::Activity;
pub use claude::BRIEF_EFFORT;
pub use claude::BRIEF_MODEL;
pub use claude::CHAT_INSTRUCTION;
pub use claude::Cancel;
pub use claude::ChatAgent;
pub use claude::ClaudeAgent;
pub use claude::Converses;
pub use claude::DRAFT_NOW_INSTRUCTION;
pub use claude::DRAFTING_CONTRACT;
pub use claude::DRAFTING_ONE_SHOT_CONTRACT;
pub use claude::DRAFTING_ROUNDS;
pub use claude::Drafted;
pub use claude::Drafting;
pub use claude::INVOCATION_TIMEOUT;
pub use claude::NOTHING_SETTLES_IT;
pub use claude::Replied;
pub use claude::WRITE_INSTRUCTION;
pub use claude::Wired;
pub use claude::brief_instruction;
pub use claude::drafting_opening;
pub use claude::proposing_instruction;
pub use colour::colour_for;
pub use composer::COMPOSER_MAX_ROWS;
pub use composer::Composed;
pub use composer::Composer;
pub use composer::ComposerWindow;
pub use composer::Pasted;
pub use composer::compose_for;
pub use composer::paste_for;
pub use confirm::Answer;
pub use confirm::Answered;
pub use confirm::Filing;
pub use confirm::PushAnswered;
pub use confirm::PushConfirm;
pub use confirm::QuitConfirm;
pub use confirm::answer_for;
pub use confirm::push_answer_for;
pub use linear::Client as LinearClient;
pub use linear::Error as LinearError;
pub use linear::FetchedProject;
pub use linear::Issue as LinearIssue;
pub use linear::NewIssue;
pub use linear::NewProject;
pub use linear::Posts;
pub use linear::Project as LinearProject;
pub use linear::REQUEST_TIMEOUT;
pub use linear::backlog_state;
pub use linear::backlog_status;
pub use linear::comment_on_project;
pub use linear::create_issue;
pub use linear::create_project;
pub use linear::create_relation;
pub use linear::fetch_project;
pub use linear::issue_label_id;
pub use linear::label_id;
pub use linear::team_id;
pub use panel::Mode;
pub use panel::Panel;
pub use prompt::Edited;
pub use prompt::RecordEdited;
pub use prompt::RecordField;
pub use prompt::RecordForm;
pub use prompt::RecordPrompt;
pub use prompt::ScopeField;
pub use prompt::ScopePrompt;
pub use prompt::edit_for;
pub use prompt::record_edit_for;
pub use selection::Cell;
pub use selection::Position;
pub use selection::Selection;
pub use selection::Span;
pub use selection::Window;
pub use selection::copied_text;
pub use selection::position_at;
pub use selection::spans_at;
pub use submission::Submitted;
pub use submission::submitted_for;
pub use template::DEFAULT_TEMPLATE;
pub use template::Error as TemplateError;
pub use template::brief_template;
pub use template::missing_sections;
pub use thread::Ending;
pub use thread::Thread;
pub use thread::Turn;
pub use thread::ending_for;
pub use ui::Hit;
pub use ui::Reach;
pub use ui::composer_height;
pub use ui::composer_on_screen;
pub use ui::draw;
pub use ui::hit_test;
pub use ui::panel_height;
pub use ui::panel_reach;
pub use ui::panel_width;
pub use ui::run_header_height;
pub use ui::tree_height;
pub use watch::COALESCED_RELOADS;
pub use watch::NodeSet;
pub use watch::QUIET_PERIOD;
pub use watch::RELOAD_CEILING;
pub use watch::Watch;
pub use watch::WatchPolicy;
pub use watch::Watching;
